<?php
/**
 * Copyright (c) 2025 Fusion Lab G.P
 * Website: https://fusionlab.gr
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** @var \FusionLab\BestPrice\Block\Head $block */
/** @var \Magento\Framework\Escaper $escaper */

?>

<!-- START Best Price 360 Analytics -->

<script type="text/javascript">
    (function (a, b, c, d, s) {a.__bp360 = c;a[c] = a[c] || function (){(a[c].q = a[c].q || []).push(arguments);};
        s = b.createElement('script'); s.async = true; s.src = d; (b.body || b.head).appendChild(s);})
    (window, document, 'bp', 'https://360.bestprice.gr/360.js');
    bp('connect', '<?php echo $escaper->escapeHtml($block->getAnalyticsId()); ?>');
    bp('native', true);

</script>

<!-- END Best Price 360 Analytics -->
